### ISSUE TITLE
Only works with piVPN install?

### ISSUE THREAD

**Issue by MunkeyBalls** [alfiosalanitri/wireguard-client-connection-notification#1]
Is it only possible to use this script when installing via pivpn? I'm using the docker image found [here](https://github.com/linuxserver/docker-wireguard). The script isn't working because clients.txt doesn't exist. After some searching it seems the file is generated by pivpn to add user friendly commands.

I still want to see if I can get your script working within my docker container. Do you think the script will work if I manually create the files? Could you show me what the clients.txt file looks like (obfuscate your keys obviously). Probably missing the CLIENT_NAME.txt file as well, could you show me the contents this one too?

**Comment by alfiosalanitri** [comment]
> looks

Can you try if now works? Thanks.

**Comment by MunkeyBalls** [comment]
That was fast, thanks!

The following line was still giving me some issues because the directory doesn't exist and doesn't contain the keys
https://github.com/alfiosalanitri/wireguard-client-connection-notification/blob/870a08b42541cecfd0a54926b5dfeb27eae9b885/wg-clients-guardian.sh#L45-L46

I think this might be because of the way the docker sets up the config files opposed to a normal wireguard install. 
The config for the docker container is actually stored in /config/ with only the wg0.conf file symlinked to /etc/wireguard/

```
root@c5f31b130d55:/# ls /config -l
drwxr-xr-x 2 abc abc 4096 Jun  6 14:12 coredns
drwxrwxr-x 2 abc abc 4096 Jun  6 17:14 custom-cont-init.d
drwx------ 2 abc abc 4096 Jun  6 14:12 peer1
drwx------ 2 abc abc 4096 Jun  6 14:12 peer2
drwx------ 2 abc abc 4096 Jun  6 14:12 peer3
drwxr-xr-x 2 abc abc 4096 Jun  6 14:12 server
drwxr-xr-x 2 abc abc 4096 Jun  6 14:12 templates
-rw------- 1 abc abc  685 Jun  6 14:12 wg0.conf
```
```
root@c5f31b130d55:/# ls /etc/wireguard/ -l
lrwxrwxrwx 1 root root   16 Jun  6 17:34 wg0.conf -> /config/wg0.conf
```

After I created the /etc/wireguard/keys directory and copied the publickey file from the /config/peer{#} folders into it the script is working perfectly, thanks!

**Comment by alfiosalanitri** [comment]
Perfect. Thank you.

**Comment by MunkeyBalls** [comment]
I noticed I didn't get any notification when connecting with a different client from the one I tested with initially.

```
root@311d7e2170f7:/config# ./wg-clients-guardian.sh 
./wg-clients-guardian.sh: line 51: /config/clients/publickey-peer2:keystringwashere/morekey=.txt: No such file or directory
```
Here's the bit of code where it starts failing:
https://github.com/alfiosalanitri/wireguard-client-connection-notification/blob/870a08b42541cecfd0a54926b5dfeb27eae9b885/wg-clients-guardian.sh#L48-L50

I'm pretty sure it's the '/'  character in this specific public key. Probably makes sense to remove all forward slashes from the CLIENT_NAME before looking up / creating the file.

**Comment by MunkeyBalls** [comment]
I've added 
```
CLIENT_NAME=$(echo "$a" | sed -e 's./..g' <<< "${CLIENT_NAME}")
```
after the line 
```
CLIENT_NAME="$(grep -R "$PUBLIC_KEY" /etc/wireguard/keys/ | awk -F"/etc/wireguard/keys/|_pub:" '{print $2}')"
```
And it's working :)

**Comment by alfiosalanitri** [comment]
Thanks for feedback. I've added the line.
